[package]
name = "emitter"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.2", directory="noir-projects/aztec-nr/aztec" }
# wormhole = { git="https://github.com/NethermindEth/wormhole", tag="v3.0.0-devnet.2", directory="aztec/contracts" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.2", directory = "noir-projects/noir-contracts/contracts/app/token_contract"}