[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
remappings = [
    "wormhole-foundation/=lib/wormhole/",
    "wormhole/=lib/wormhole/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"